### ISSUE TITLE
Roadmap needed

### ISSUE THREAD

**Issue by bhushan** [Wulfheart/pretty-routes#22]
I like this package I want to contribute to it but this package is going crazily in different directions with each PR. Each PR is with a different implementation strategy. Once @Wulfheart decides the path to go with which PRs. I will share the next PRs, as I am not sure which implementations you will keep.

I think we should have some kind of roadmap or something.. 

@Gummibeer @Wulfheart what you guys think about this?

**Comment by Gummibeer** [comment]
I agree - right now it's a "throw together" of every PR. Most contributors change styles, remove or add type hints and so on.

I'm not sure which capacity Alex has? As I have ~30 packages my own to maintain I can't handle another foreign one. So I could offer a move to @Astrotomic or my help from time to time.

But I agree that the maintainer should have a roadmap and potentially also reject features and enforce wanted rules.

To make testability easier I would also go for classes like `RouteProvider` and `MethodFormatter` and other single task classes.
The current snapshots are partially buggy and we're only the fastest way to test the whole command.

**Comment by Wulfheart** [comment]
Thanks for the offer @Gummibeer and also thank you for your support. Right now I'm planning to seize the opportunity to learn how to maintain an open source project.

I don't feel the need to extract functionality in separate classes as the Laravel Core does that neither. However, some methods of the command could be tested properly. Therefore I'm proposing the following roadmap:

- [ ]  Add PHP CS Fixer (#16)
- [ ] Write a `contributing.md` (#16)
- [ ] `--only-path`, `--except-path`, `--only-name`, `--except-name` compatability in between them or at least locks between them
- [ ] `--only-path`, `--except-path`, `--only-name`, `--except-name` comma separated values support
- [ ]  Add a group feature to group by route name and uri
- [ ] Write tests based on #19

**Comment by Wulfheart** [comment]
This roadmap should now be done,
